name: caching-deps
description: get and cache deps

inputs:
  title:
    description: Cache Key
    required: true
    default: 'app_index'

outputs:
  hit:
    description: Whether existing cache been hit
    value: ${{ steps.cached.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      id: cached
      with:
        key: ${{ inputs.title }}_${{ hashFiles('index.js') }}
        path: index.js
    - run: cat index.js
      shell: bash
      if: steps.cached.outputs.cache-hit != 'true'
