name: test1
run-name: test1 run by @${{ github.actor }}

on:
  - workflow_dispatch
  - push

env:
  PIPE: cicd

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: test step1
        run: echo "${{ github.ref }}, ${{ runner.name }}, ${{ runner.os }}"
      - name: test step1
        run: echo "${{ github.workspace }}, ${{ job.status }}"
      - name: test step1
        run: echo "$RUNNER_OS, $PIPE"
