name: test1
run-name: test1 run by @${{ github.actor }}

on:
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: test step1
        run: ls
