name: caching

on: [workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        id: cached
        with:
          key: app_index_${{ hashFiles('index.js') }}
          path: index.js
      - run: cat index.js
        if: steps.cached.outputs.cache-hit != 'true'

  jobs2:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "${{ vars.MY_APP }}"
