name: conditional

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: |
          echo "1"
          ls /no
        id: list
        continue-on-error: true
      - run: echo "2"
        if: success() && steps.list.outcome == 'success'
      - run: echo "3"
        if: failure() && steps.list.outcome == 'failure'

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: success()
    steps:
      - run: echo "job2"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    if: failure()
    steps:
      - run: echo "job3"
