name: conditional

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: |
          echo "1"
          ls /no
      - run: echo "2"
        continue-on-error: true
      - run: echo "3"
        continue-on-error: true
