name: Fifth Action

on:
  - workflow_dispatch

env:
  MY_ENV_VAR: one

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: job name
        run: echo ${{ github.job }}
      - name: print secret
        run: echo ${{ secrets.DB_PASS }}
      - name: print var
        run: echo ${{ vars.MY_VAR }}
      - name: print env var
        run: echo $MY_ENV_VAR

  job2:
    needs:
      - job1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v4
      - name: job name
        run: echo ${{ github.job }}
      - name: run script
        run: |
          chmod +x ./my.sh
          ./my.sh

  job3:
    if: always()
    needs:
      - job1
      - job2
    runs-on: ubuntu-latest
    steps:
      - name: job name
        run: echo ${{ github.job }}
