name: Fifth Action

on:
  - push
  - workflow_dispatch

defaults:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job name
        run: echo ${{ github.job }}
      - name: print secret
        run: echo ${{ secrets.DB_PASS }}
      - name: print var
        run: echo ${{ vars.MY_VAR }}

  job2:
    needs:
      - job1
    runs-on: ubuntu-latest
    steps:
      - name: job name
        run: echo ${{ github.job }}

  job3:
    if: always()
    needs:
      - job1
      - job2
    runs-on: ubuntu-latest
    steps:
      - name: job name
        run: echo ${{ github.job }}
