name: Fifth Action

on:
  - push
  - workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job name
        run: ${{ github.job }}

  job2:
    needs:
      - job1
    runs-on: ubuntu-latest
    steps:
      - name: job name
        run: ${{ github.job }}

  job3:
    if: always()
    needs:
      - job1
      - job2
    runs-on: ubuntu-latest
    steps:
      - name: job name
        run: ${{ github.job }}
