name: "First Action"

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "First"
      - name: Second Step
        run: echo "Second"
