name: First Action

on:
  workflow_dispatch:
    inputs:
      print_hash:
        description: "if hash should be printed"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - name: show test
        run: ls test.txt

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: hash file
        run: sha1sum test.txt > hashed.txt
      - name: upload hashed file
        uses: actions/upload-artifact@v4
        with:
          name: hash_artifact
          path: hashed.txt
          if-no-files-found: error
          retention-days: 3
          overwrite: true

  printHash:
    if: ${{ inputs.print_hash }}
    runs-on: ubuntu-latest
    steps:
      - name: download hash
        uses: actions/download-artifact@v4
        with:
          name: hash_artifact
      - name: print hash
        run: cat hashed.txt
