name: First Action

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - name: show test
        run: ls test.txt
