name: Fourth Action

on:
  workflow_dispatch:
  push:

jobs:
  using_context:
    runs-on: ubuntu-latest
    env:
      MY_ACTION: ${{ github.action }}
    steps:
      - run: echo $MY_ACTION
      - run: echo ${{ github.action }}
