name: in docker

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node -v
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: 'false'
