name: Second Action
run-name: Second Action Run Name

on:
  repository_dispatch:
    types:
      - webhook

  workflow_dispatch:
    inputs:
      logLevel:
        description: Log Level
        required: true
        default: warning
        type: choice
        options:
          - error
          - warning
          - info
          - debug
      printTags:
        description: Print Tags
        required: true
        type: boolean

jobs:
  print:
    runs-on: ubuntu-latest
    name: Print something
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: First step
        run: ls -alh
