name: Second Action

on:
  push:
    branches:
      - main
      - dev
      - test
  workflow_dispatch: 

jobs:
  print:
    runs-on: ubuntu-latest
    name: Print something
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: First step
        run: ls -alh
