name: third action

on:
  workflow_dispatch:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'kryz81/test_github')
    steps:
      - name: test
        run: echo "first job works"

  second:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.repository, 'kryz81/test_github') }}
    steps:
      - name: test
        run: echo "second job shouldn't work"

  third:
    runs-on: ubuntu-latest
    steps:
      - if: success()
        run: echo "success"
      - if: failure()
        run: echo "failure"
      - if: always()
        run: echo "always"
