name: third action

on:
  workflow_dispatch:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'kryz81/test_github')
    steps:
      - name: test
        run: echo "first job works"

  second:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.repository, 'kryz81/test_github') }}
    steps:
      - name: test
        run: echo "second job shouldn't work"

  third:
    runs-on: ubuntu-latest
    steps:
      - if: success() # true when all previous steps of this succeeded
        run: echo "success"
      - if: failure() # true when any previous steps of this job fails
        run: echo "failure"
      - if: always()
        run: echo "always" # step executes always even if job cancelled
      - if: cancelled()
        run: echo "cancelled" # step executes always only when job has been cancelled

  fourth:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: hash test
        run: echo "hash is: ${{ hashFiles('test.txt') }}"
